SERVICE_REGISTRY:
  URL: http://service-registry:8761/eureka
LOG:
  ENABLED: true

###########################
log:
  request:
    enabled: ${LOG.ENABLED}     # enable logging for request/response
    
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY.URL}

spring:
  cloud:
    gateway:
      routes:
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/api/*/sessions/**
        - id: speaker-service
          uri: lb://speaker-service
          predicates:
            - Path=/api/*/speakers/**
        - id: tag-service
          uri: lb://tag-service
          predicates:
            - Path=/api/*/tags/**
        - id: timeslot-service
          uri: lb://timeslot-service
          predicates:
            - Path=/api/*/timeslots/**
        - id: workshop-service
          uri: lb://workshop-service
          predicates:
            - Path=/api/*/workshops/**
        - id: attendee-ticket-service
          uri: lb://attendee-ticket-service
          predicates:
            - Path=/api/*/attendeeTickets/**
