DB:
  TYPE: POSTGRESQL
  URL: jdbc:postgresql://localhost:9106/ATTEND_TICKET_SERVICE_DB
  USERNAME: postgres
  PASSWORD: Welcome
ZIPKIN:                                   # zipkin
  URL: http://localhost:9411
SERVICE_REGISTRY:                         # eureka
  URL: http://localhost:8761/eureka

spring:
  jpa:
    database: ${DB.TYPE}
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  zipkin:
    base-url: ${ZIPKIN.URL}
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY.URL}
