DB:
  TYPE: POSTGRESQL
  CONNECTION_URL: jdbc:postgresql://localhost:9104/SESSION_SERVICE_DB
  USERNAME: postgres
  PASSWORD: Welcome
SERVICE_REGISTRY_URL: http://localhost:8761/eureka
ZIPKIN_URL: http://localhost:9411/
