DB:
  TYPE: POSTGRESQL
  URL: jdbc:postgresql://localhost:9103/SPEAKER_SERVICE_DB
  USERNAME: postgres
  PASSWORD: Welcome
ZIPKIN:
  URL: localhost:9411
SERVICE_REGISTRY:
  URL: localhost:8761/eureka
