DB:
  TYPE: POSTGRESQL
  URL: jdbc:postgresql://speaker-service-db/SPEAKER_SERVICE_DB
  USERNAME: postgres
  PASSWORD: Welcome
ZIPKIN:                                   # zipkin
  URL: openzipkin
SERVICE_REGISTRY:                         # eureka
  URL: service-registry/eureka

spring:
  jpa:
    database: ${DB.TYPE}
    show-sql: true
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  zipkin:
    base-url: ${ZIPKIN.URL}
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY.URL}
